{
  "hash": "67098b2d2f0f93412fbd6689432d87aa",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic Regression\"\ndate: 3/11/25\nformat:\n  revealjs:\n    width: 1200\n    scrollable: true\n    theme: [default, styles.scss]\n    navigation-mode: vertical\n    controls-layout: bottom-right\n    controls-tutorial: true\n    incremental: false \n    chalkboard:\n      theme: whiteboard\n      chalk-width: 4\nknitr:\n  opts_chunk: \n    echo: true\n    eval: true\n    message: false\n    code-fold: true\n    warnings: false\n    comment: \"#>\" \n    \nrevealjs-plugins:\n  - pointer\n  - verticator\n  \nfilters: \n  - reveal-header\n  - code-fullscreen\n  - reveal-auto-agenda\neditor: source\n---\n\n\n\n\n\n# Motivation\n\n## Melanoma\n\nMelanoma is a type of skin cancer that causes the cells that produce melanin to grow out of control. What makes Melanoma so dangerous is that it can metastasize to other parts of the body.\n\n## Outcome of Interest\n\nWe are interested in learning how do different factors affect and individual's chances of survival. Therefore, we are measuring patients and if they lived or died during a study period.\n\n## Data \n\nWe will be using the `Melanoma` data set with the following variables: `dead` (died by Melanoma, 1=yes, 0= no),  `sex` (1 = male, 0 = female), `age` (in years), `thickness` (tumour thickness in mm), ulcer (1 = presence, 0 absent).\n\n## Plot\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nMelanoma |> \n  ggplot(aes(thickness, dead)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](8_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n\n# Modeling Binary Outcomes\n\n## Construct Model\n\n$$\n\\left(\\begin{array}{c}\nDead \\\\\nAlive\n\\end{array}\\right) = \\beta_0 + \\beta_1X\n$$\n\n## Let ...\n\n$$\nY = \\left\\{\\begin{array}{cc}\n1 & Dead \\\\\n0 & Alive\n\\end{array}\\right.\n$$\n\n## Construct a Model\n\n$$\nP\\left(Y = 1\\right) = \\beta_0 + \\beta_1X\n$$\n\n## Construct a Model\n\n$$\nP\\left(Y = 1\\right) = \\frac{e^{\\beta_0 + \\beta_1X}}{1 + e^{\\beta_0 + \\beta_1X}}\n$$\n\n## Construct a Model\n\n$$\n\\frac{P(Y = 1)}{P(Y = 0)} = e^{\\beta_0 + \\beta_1X}\n$$\n\nwhere $\\frac{P(Y = 1)}{P(Y = 0)}$ are considered the odds of observing $Y = 1$.\n\n## The Logistic Model\n\n$$\n\\log\\left\\{\\frac{P(Y = 1)}{P(Y = 0)}\\right\\} = \\beta_0 + \\beta_1X\n$$\n\n\n# Logistic Regression\n\n## Logistic Regression\n\nLogistic Regression is used to model the association between a set of predictors and a **binary** outcome variable.\n\n::: fragment\nThis is similar Linear Regression which models the association between a set of predictors and a **numerical** outcome variable.\n:::\n\n## Logistic Regression\n\nLogistic Regression uses the logistic model to formulate the relationship between the predictors and the outcome.\n\n::: fragment\n\nMore specifically, for an outcome of Y:\n\n$$\nY = \\left\\{\\begin{array}{cc}\n1 & \\text{Category 1} \\\\\n0 & \\text{Category 2}\n\\end{array}\\right.\n$$\n\nThe Predictors variable will model the probability of observing category 1 ($P(Y=1)$)\n\n:::\n\n\n## Logistic Model\n\n$$\n\\log\\left\\{\\frac{P(Y = 1)}{P(Y = 0)}\\right\\} = \\beta_0 + \\beta_1X\n$$\n\n## Regression Coefficients $\\beta$\n\nThe regression coefficients quantify how a specific predictor changes the odds of observing the first category of the outcome ($Y = 1$)\n\n## Estimating $\\beta$\n\nTo obtain the numerical value for $\\beta$, denoted as $\\hat \\beta$, we will be finding the values of $\\hat \\beta$ that maximizes the likelihood function:\n\n$$\nL(\\boldsymbol \\beta) = \\prod_{i=1}^n \\left(\\frac{e^{\\beta_0 + \\beta_1X}}{1 + e^{\\beta_0 + \\beta_1X}}\\right)^{Y_i}\\left(\\frac{1}{1 + e^{\\beta_0 + \\beta_1X}}\\right)^{1-Y_i}\n$$\n\nThe likelihood function can be thought as the probability of observing the entire data set. Therefore, we want to choose the values the $\\beta_0$ and $\\beta_1$ that will result in the highest probability of observing the data.\n\n\n## Estimated Parameters\n\nThe values you obtain ($\\hat \\beta$) tell you the relationship between the a predictor variable and the log odds of observing the first category of the outcome $Y=1$.\n\n::: fragment\nExponentiating the estimate ($e^{\\hat \\beta}$) will give you the relationship between a predictor variable and the odds of observing the first category of the outcome $Y=1$.\n:::\n\n## Interpreting $\\hat \\beta$\n\nFor a continuous predictor variable:\n\nAs X increases by 1 unit, the odds of observing the first category ($Y = 1$) increases by a factor of $e^{\\hat\\beta}$.\n\nFor a categorical predictor variable (first dummy variable):\n\nThe odds of observing the first category ($Y = 1$) in the indicated category ($D=1$) is $e^{\\hat\\beta}$ times higher/lower compared to the reference category ($D=0$).\n\n\n## Logistic Regression in R\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglm(Y ~ X1 + X2 + ... + Xp,\n    data = DATA,\n    family = binomial())\n```\n:::\n\n\n\n\n## Example\n\nModelling `dead` by `sex`, `age`, `thickness`, and `ulcer`: \n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nglm(dead ~ sex + age + thickness + ulcer,\n    data = Melanoma,\n    family = binomial())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:  glm(formula = dead ~ sex + age + thickness + ulcer, family = binomial(), \n#>     data = Melanoma)\n#> \n#> Coefficients:\n#> (Intercept)          sex          age    thickness        ulcer  \n#>    -2.39860      0.40767      0.00402      0.11253      1.31314  \n#> \n#> Degrees of Freedom: 204 Total (i.e. Null);  200 Residual\n#> Null Deviance:\t    242.4 \n#> Residual Deviance: 210.3 \tAIC: 220.3\n```\n\n\n:::\n:::\n\n\n\n$$\n\\log(odds) = -2.40 + 0.41 M + 0.004 age + 0.11 thick + 1.31ulc\n$$\n\n\n## Interpretation\n\n$$\n\\log(odds) = -2.40 + 0.41 M + 0.004 age + 0.11 thick + 1.31ulc\n$$\n\n::: fragment\nThe odds of experiencing death in males is 1.5 times larger than the odds for females, adjusting for age, tumor thickness and the presence of an ulcer.\n:::\n\n::: fragment\nAs age increases by 1 year, the odds of experiencing death increases by a factor of 1.004, adjusting for sex, tumor thickness and presence of an ulcer.\n:::\n\n# Prediction with Models\n\n## Working with probabilities\n\nAs you can see, working with odds may be unintuitive for the average person. It will be better to predict the probability and display those results to individuals.\n\n## Predicting Probability\n\n\n$$\n\\hat P\\left(Y = 1\\right) = \\frac{e^{\\hat\\beta_0 + \\hat\\beta_1X_1 + \\cdots  + \\hat \\beta_pX_p}}{1 + e^{\\hat\\beta_0 + \\hat\\beta_1X_1 + \\cdots  + \\hat \\beta_pX_p}}\n$$\n\n## Prediction in R\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxglm <- glm(Y ~ X1 + X2 + ... + Xp,\n            data = DATA,\n            family = binomial())\npredict_df <- data.frame(X1 = VAL,  X2 = VAL, ..., Xp = VAL)\npredict(xglm,\n        predict_df,\n        type = \"response\")\n```\n:::\n\n\n\n\n## Example 1\n\nPredict the probability of observing death for a patient who is male, 75 years old, an tumor thickness of 2.9, and **with** ulcer presence. \n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxglm <- glm(dead ~ sex + age + thickness + ulcer,\n    data = Melanoma,\n    family = binomial())\npredict_df <- data.frame(sex = 1, age = 75, thickness = 2.9, ulcer = 1)\npredict(xglm, predict_df, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         1 \n#> 0.4875223\n```\n\n\n:::\n:::\n\n\n\n\n## Example 1\n\nPredict the probability of observing death for a patient who is male, 75 years old, an tumor thickness of 2.9, and **without** ulcer presence. \n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxglm <- glm(dead ~ sex + age + thickness + ulcer,\n    data = Melanoma,\n    family = binomial())\npredict_df <- data.frame(sex = 1, age = 75, thickness = 2.9, ulcer = 0)\npredict(xglm, predict_df, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         1 \n#> 0.2037438\n```\n\n\n:::\n:::\n\n\n\n\n## Example 1\n\n| | Ulcer Present | Ulcer not Present |\n|:-|:-|:-|\n| Probabiltiy | 48.7% | 20.3% |\n\nFor a patient who is 75 years old, male, and a tumor thickness of 2.9, when an ulcer is present, the probability a patient dies increases to 48% compared to a patient who does not have an ulcer with a probability of 20%.\n\n\n## Example 2\n\nPredict the probability of observing death for a patient who is female, **75** years old, an tumor thickness of 2.9, and with ulcer presence. \n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxglm <- glm(dead ~ sex + age + thickness + ulcer,\n    data = Melanoma,\n    family = binomial())\npredict_df <- data.frame(sex = 0, age = 75, thickness = 2.9, ulcer = 1)\npredict(xglm, predict_df, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         1 \n#> 0.3875575\n```\n\n\n:::\n:::\n\n\n\n\n## Example 2\n\nPredict the probability of observing death for a patient who is female, **55** years old, an tumor thickness of 2.9, and with ulcer presence. \n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nxglm <- glm(dead ~ sex + age + thickness + ulcer,\n    data = Melanoma,\n    family = binomial())\npredict_df <- data.frame(sex = 0, age = 55, thickness = 2.9, ulcer = 1)\npredict(xglm, predict_df, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>         1 \n#> 0.3686531\n```\n\n\n:::\n:::\n\n\n\n## Example 2\n\n| | 55 | 75 |\n|:-|:-|:-|\n| Probabiltiy | 36.8% | 38.7% |\n\nFor a patient who is female, a tumor thickness of 2.9, and has an ulcer, the probability a 75 year old patient dies increases to 38.7% compared to a 55 year old patient with a probability of 36.8%.\n\n",
    "supporting": [
      "8_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}