{
  "hash": "c60d06012d2d818e662a01c905d54f6c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear Models\"\nformat:\n  revealjs:\n    scrollable: true\n    theme: [default, styles.scss]\n    navigation-mode: vertical\n    controls-layout: bottom-right\n    controls-tutorial: true\n    incremental: false \n    chalkboard:\n      src: notes/chalkboard_1a.json\n      storage: chalkboard_pres\n      theme: whiteboard\n      chalk-width: 4\nknitr:\n  opts_chunk: \n    echo: false\n    eval: true\n    message: false\n    warnings: false\n    comment: \"#>\" \n    \nrevealjs-plugins:\n  - pointer\n  - verticator\n  \nfilters: \n  - reveal-header\n  - code-fullscreen\n  - reveal-auto-agenda\n  \nauto-agenda:\n  bullets: numbered\n  heading: Learning Outcomes\n  \neditor: visual\n---\n\n\n\n\n\n\n\n# Announcements\n\n## Scorpio Season is Here!!\n\nThe first 6 reading assignments and quizzes are open for retakes until October 31!\n\n::: fragment\n**This is your last chance!!**\n:::\n\n::: fragment\n**No more new chances will be coming for remaining of semester.**\n:::\n\n::: fragment\n**Other Assignment are still due.**\n:::\n\n## Plotathon\n\n![](img/PAT24%20L&L%20Tools%20Workshop.png){fig-align=\"center\"}\n\n# Group Models\n\n## Group Models\n\nThe independent variables are used to indicate groups.\n\n## Danceability Model\n\n$$\n\\hat Y_i = 0.6185 - 0.0455 X - 0.1095 Z \n$$\n\n$$\nZ = \\left\\{\\begin{array}{cc}\n1 & Speak\\ Now\\\\\n0 & Other\n\\end{array}\n\\right.\n$$\n\n$$\nX = \\left\\{\\begin{array}{cc}\n1 & Midnights\\\\\n0 & Other\n\\end{array}\n\\right.\n$$\n\n# Linear Relationship\n\n## Scatter Plot\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11a_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n\n\n## Positive Linear Relationship\n\n## Scatter Plot\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11a_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n\n## Negative Linear Relationship\n\n# Modelling Linear Relationship\n\n## Modelling Linear Relationship\n\n## Regression Models\n\n$$\n\\hat Y _i = b_0 + b_1 X_i\n$$\n\n$X_i$ is a continuous variable, not groups\n\n## Interpreting Intercept\n\n## Interpreting Slope\n\n# Motivating Example: Coffee\n\n## Motivating Example: Coffee\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11a_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\n\n## Fitting a Linear Model in R\n\nUse the `lm()` function\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(Y ~ X, data = data_set)\n```\n:::\n\n\n\n\n\n## Fitting a Linear Model\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11a_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n\n## Fitting a Linear Model in R\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(flavor ~ aroma, data = coffee_aroma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> lm(formula = flavor ~ aroma, data = coffee_aroma)\n#> \n#> Coefficients:\n#> (Intercept)        aroma  \n#>      1.1372       0.8435\n```\n\n\n:::\n:::\n\n\n\n\n\n## Fitting a Linear Model\n\n$$\n\\hat Y = 1.1372 + 0.8435 X\n$$\n\n$$\nX = \\mathrm{AROMA\\ Score}\n$$\n\n$$\n\\hat Y = \\mathrm{Predicted\\ Flavor\\ Score}\n$$\n\n## Interpreting Intercept\n\n$$\n\\hat Y = 1.1372 + 0.8435 X\n$$\n\n## Interpreting Slope\n\n$$\n\\hat Y = 1.1372 + 0.8435 X\n$$\n\n## Predicting Value for given X\n\n$$\n\\hat Y = 1.1372 + 0.8435 X\n$$\n\n# EPE Session\n\n## Study Habits for the Exam\n",
    "supporting": [
      "11a_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}